### PR TITLE
Fix bounds

### PR DESCRIPTION
**Pull request by lspitzner**
I checked all the bounds for new releases, and was able to switch to latest versions for all of them, without any code changes necessary. Fixed one warning. Builds fine with ghc-7.10-rc2, not tested really. Did not push versions of the contained packages.

I would be fine with becoming co-maintainer on hackage; otherwise I would like a new release.

### CODE REVIEW

**Comment by divipp** [comment]
Thanks!
What is your hackage user Id? I would like to add you to the maintainer group.

**Comment by lspitzner** [comment]
same as here

**Comment by divipp** [comment]
OK, I have added lspitzner to the maintainers group of activehs and activehs-base (sorry for the delay)!

**Comment by lspitzner** [comment]
thanks!
apart from active-hs-base, there is data-pprint, dia-base and dia-functions (i'd be most interested in a new data-pprint release).

**Comment by divipp** [comment]
I added you to the maintainers of data-pprint, dia-base and dia-functions now!

**Pull request merged**
